DEFINE_THUNK(dxgi, CreateDXGIFactory)
DEFINE_THUNK(dxgi, CreateDXGIFactory1)
DEFINE_THUNK(dxgi, CreateDXGIFactory2)
DEFINE_THUNK(dxgi, DXGIDeclareAdapterRemovalSupport)
DEFINE_THUNK(dxgi, DXGIGetDebugInterface1)
